### ISSUE TITLE
This worked once but now I'm getting an error in the HA log.

### ISSUE THREAD

**Issue by healeydave** [robmarkcole/HASS-plate-recognizer#23]
Any idea's what is causing this?

Logger: homeassistant.helpers.entity
Source: custom_components/platerecognizer/image_processing.py:124 
First occurred: 16:24:45 (10 occurrences) 
Last logged: 17:07:22

Update for image_processing.platerecognizer_driveway_top fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 132, in async_update
    await self.async_process_image(image.content)
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 112, in async_process_image
    return await self.hass.async_add_executor_job(self.process_image, image)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/platerecognizer/image_processing.py", line 124, in process_image
    self._image = Image.open(io.BytesIO(bytearray(image)))
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2958, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa2e30c20>

**Comment by robmarkcole** [comment]
seems a problem with the image, possibly corrupted?

**Comment by healeydave** [comment]
Thanks. I'm not sure why that would happen. It seems to be functioning again at the moment but I don't think it works every time and I've yet to capture a working image. 

I've been messing round with the camera motion settings to try and get a vehicle in shot but its like a needle in a haystack. 

I've narrowed the motion capture area to just a few squares in the middle of the drive but it still seems to detect motion when there's either no vehicle even in view or too early when a vehicle is at the top of the drive and out of focus. My Cameras are 4K Hikvision but the images captured are only 704 x 576.

I think I've come to the conclusion that the camera position is not going to be good enough to produce an image sufficiently good enough for it to work unfortunately. Here are the best examples I've managed to get. The picture quality to atrocious and it's no wonder it's not working.

![image](https://user-images.githubusercontent.com/5435141/108820561-43622280-75b4-11eb-85cb-9b3f511c5c7b.png)

![image](https://user-images.githubusercontent.com/5435141/108820845-ae135e00-75b4-11eb-80b1-68dadd5a75d9.png)

**Comment by robmarkcole** [comment]
You could use deepstack object to detect when there is a vehicle, and only then send an image to plate recognizer.
Motion capture is notoriously difficult to fine tune. Please create a discussion on this topic as this is not a code issue. Thanks

**Comment by healeydave** [comment]
No problem and thank you. Incidentally, where would discussions on this take place please?

**Comment by robmarkcole** [comment]
created one already

![image](https://user-images.githubusercontent.com/11855322/108823708-b79ec500-75b8-11eb-91d5-864a612a50da.png)
