### ISSUE TITLE
SUGGESTION: Change /config/images/platerecognizer/ to /config/www/images/platerecognizer/ in readme

### ISSUE THREAD

**Issue by iKingRPG** [robmarkcole/HASS-plate-recognizer#29]
Love the integration, but in my opinion this would be a better default location, because then you can create local file cameras, and otherwise you can't do things like send the latest image in a notification via automation.

**Comment by robmarkcole** [comment]
In another repo I pointed to www but someone said this is a bad idea as that is insecure 😃

**Comment by iKingRPG** [comment]
> In another repo I pointed to www but someone said this is a bad idea as that is insecure 😃

Oh, that's fair.
