### ISSUE TITLE
[Feature Request] - Url or file as source instead of camera

### ISSUE THREAD

**Issue by thrawnarn** [robmarkcole/HASS-plate-recognizer#30]
It would be great to be able to use an url or a file for source instead of camera.

**Use case**
I'm using [Frigate](https://github.com/blakeblackshear/frigate) as NVR- software and when using the official HA-component for Frigate it creates all cameras in HA with a max height of 277px. I've found that that is a little bit to small for my setup when running plates. It would be great to be able to set an url directly to my Frigate instance where I can access a full resolution image of the camera feed.

**Comment by thrawnarn** [comment]
ah, I saw now in the HA-documentation that this is a HA-related limitation :(

**Comment by robmarkcole** [comment]
All of the image processing integrations work by processing a camera. I suggest the approach to take is to create a camera which displays the feed from the url, then apply this integration to _that_ camera. Re limitations, you could either create a PR to update HA or create a custom integration. Cheers
