### ISSUE TITLE
get_orientations error: 'orientation'

### ISSUE THREAD

**Issue by greberg** [robmarkcole/HASS-plate-recognizer#36]
Getting following error get_orientations error: 'orientation'. Getting this everytime a platrecognizer is triggered

Source: custom_components/platerecognizer/image_processing.py:94

Running release 1.1.0 of Plate and HA 2021.5.2

**Comment by greberg** [comment]
It seems like it is due to mmc=false. Orientation is only possible to get if you have set mmc = true. API says // Make Model, Orientation and Color are only available if you set mmc=true. The custom_component is firing def get_orientations(results : List[Dict]) -> List[str]: every time it run a platerecognizer. Should probably be a if-statement here

**Comment by robmarkcole** [comment]
Can someone create a PR?

**Comment by supajason** [comment]
PR created

**Comment by Marco2205** [comment]
Dear @robmarkcole congratulations for the project, can you confirm that orientation can only be used with the paid subscription? it's really a shame!
