### ISSUE TITLE
Thank you / 

### ISSUE THREAD

**Issue by dalewright** [robmarkcole/HASS-plate-recognizer#39]
Hey Rob

Firstly, thank you so much for this. We live on a large rural property in Australia and are using this to work out who is at our gate and automatically open the gate if we like them :)

I wondered if you had considered allowing the intergration to connect to a on-premise instance of plate recogniser (running in a docker container). 

https://app.platerecognizer.com/sdk/

I wish I knew how to code, in which case I would raise a PR and not an issue.

Please keep up the great work.

P.S. I have been working with Plate Recogniser to get a more affordable plan for plan for us all. The new plan pricing will work for Cloud and SDK licenses.

**Comment by robmarkcole** [comment]
Hi @dalewright 
great to hear this is useful to you. 
I believe all thats required is to change `PLATE_READER_URL = "https://api.platerecognizer.com/v1/plate-reader/"` to point to your local instance which will be something like `PLATE_READER_URL = "http://localhost:8080/v1/plate-reader/"`, replacing `localhost` with the appropriate IP address.

**Comment by dalewright** [comment]
Sir, you are a legend. Thank you.

I will give that a try next weekend and update you.

I've also passed this update onto the Plate Recogniser team.
