### ISSUE TITLE
ERROR (SyncWorker_20) 

### ISSUE THREAD

**Issue by gavinpbennett** [robmarkcole/HASS-plate-recognizer#42]
Firstly, I think this custom integration is awesome, thanks for the effort to keep this going. 
I have noticed this error in the logs, the request still processes and reports a recognized plate, but thought I would see if this has been reported before. Do you know what is causing this? 
ERROR (SyncWorker_20) [custom_components.platerecognizer.image_processing] get_orientations error: 'orientation'

**Comment by robmarkcole** [comment]
resolved in pr that closed https://github.com/robmarkcole/HASS-plate-recognizer/issues/36
please update
