### ISSUE TITLE
moving cars no detection

### ISSUE THREAD

**Issue by belmont** [robmarkcole/HASS-plate-recognizer#43]
any idea how to make it work with moving cars?
the object detector of Frigate detects the car earlier than the license plate would be clearly visible.
I use the Frigate object detector as binary sensor to trigger the license plate recognizer.
I feed the frigate camera to the plate recognizer but it never picks a photo that is close enough to recognize the number plate.

Basically I am trying to use 2 object detector, one for recognizing cars (done by Frigate) and another to recognize the number plate (using this)

**Comment by robmarkcole** [comment]
Assume you will need to process every frame where a car is present. Please open this topic as a discussion not an issue. Thanks
