### ISSUE TITLE
Watched Plates Sensor Issue

### ISSUE THREAD

**Issue by htiennhan** [robmarkcole/HASS-plate-recognizer#46]
I can get plate recognizer to work with my home assistant however I am having issue when adding watched plates sensor

Below is my sensor code 

sensor:
  - platform: template
    sensors:
      plate_recognizer:
        friendly_name: "abc12d"
        value_template: "{{ state_attr('image_processing.platerecognizer_1', 'watched_plates').abc12d }}"

Home Assistant having this warning in the log 
![image](https://user-images.githubusercontent.com/73723274/134812348-d82a7f44-2bba-47af-b3ca-c8a52c789751.png)

When I scan plate-recognizer, it can detect my license plate but the sensor does not change state. 
 My home assistant version is core-2021.9.0b6.

**Comment by robmarkcole** [comment]
this returns None: `state_attr('image_processing.platerecognizer_1', 'watched_plates')`

**Comment by htiennhan** [comment]
Hi Rob,

Sorry, maybe I misunderstanding the usage of the sensor.
All I am trying to do is to trigger an action when my license plate is detected.  
I thought the sensor will return the state to "true" when 'watched_plates' detected 'abc12d', and return state to "false" when "watched_plates" is not 'abc12'.

**Comment by htiennhan** [comment]
Just found out that I missed spelled the image_processing entity. the watched plates sensor works fine
