### ISSUE TITLE
Coordinates of detected plate box

### ISSUE THREAD

**Issue by holdestmade** [robmarkcole/HASS-plate-recognizer#47]
Looking on Platerecognizer's website, it says it returns coordinates of the detected plate box, is this possible to add ?

The centre of the box would suffice, I would like to check where each plate is detected (drive or road)

<html>
<body>

results/box | Bounding box for the license plate. Coordinates in pixel of the top left and bottom right corners of the plate.
-- | --

</body>
</html>

**Comment by robmarkcole** [comment]
merged
