### ISSUE TITLE
Warning device_state_attributes after update to 2021.12

### ISSUE THREAD

**Issue by gulli1986** [robmarkcole/HASS-plate-recognizer#50]
Getting the following warning after update to 2021.12:

`2021-12-11 21:53:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity image_processing.platerecognizer_driveway (<class 'custom_components.platerecognizer.image_processing.PlateRecognizerEntity'>) implements device_state_attributes. Please report it to the custom component author.`

It looks like it is just a name change from "device_state_attributes" to "extra_state_attributes" name change.
Anyone knows how to fix this? Is it just to replace all "device_state_attributes" by "extra_state_attributes" in all files?

**Comment by robmarkcole** [comment]
Do robmarkcole/HASS-Deepstack-object#261 here
