### ISSUE TITLE
Camera not found?

### ISSUE THREAD

**Issue by isidororeyes** [robmarkcole/HASS-plate-recognizer#53]
Hello

I'm not able to upload the pictures to platerecognizer, from the logs it seems camera is not found. I'm sure the setup is correct! 
It was working a couple of day ago

See some logs below
Logger: homeassistant.components.image_processing
Source: components/image_processing/__init__.py:134
Integration: Image processing (documentation, issues)
First occurred: 10:50:42 PM (2 occurrences)
Last logged: 10:52:39 PM

Error on receive image from entity: Camera not found
Error on receive image from entity: Unable to get image

This is the relevant part of the config
image_processing:
  - platform: platerecognizer
    api_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    regions:
      - es
    save_file_folder: /media/plates
    save_timestamped_file: True
    always_save_latest_file: True
    detection_rule: strict
    region: strict
    source:
      - entity_id: camera.camino

And the entity camera.camino in dev tools returns the right information...

access_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
frontend_stream_type: hls
backlight_state: OFF
daynight_state: AUTO
sensitivity: 
- id: 0
  sensitivity: 10
  begin: '00:00'
  end: '06:00'
- id: 1
  sensitivity: 10
  begin: '06:00'
  end: '12:00'
- id: 2
  sensitivity: 10
  begin: '12:00'
  end: '18:00'
- id: 3
  sensitivity: 10
  begin: '18:00'
  end: '23:59'

video_url: /api/reolink_dev/vod/44108bcc795fc8ca6efdf135174cf1a7/Rec_20220114_185744_411_M.mp4
entity_picture: /api/camera_proxy/camera.camino?token=d0f58f776d8ee1c14aa506507db8996d3b06644c02dfa41c09a85bac0e4d075c
friendly_name: camino
supported_features: 2050

On a side note, camera.camino changed IP recently. 
Any ideas?  
Thanks

**Comment by robmarkcole** [comment]
This sounds like an issue with your camera integration, please ask on the forums, thanks
