### ISSUE TITLE
All attributes missing from image_processing entity

### ISSUE THREAD

**Issue by holdestmade** [robmarkcole/HASS-plate-recognizer#62]
Since updating to 2022.4.b0 All attributes missing from `image_processing` entity. State works OK and is showing the number of plates.

Set logging to debug and only shows this:

`2022-03-31 17:38:12 DEBUG (SyncWorker_17) [custom_components.platerecognizer.image_processing] Config: {"detection_rule": "strict", "region": "False"}`

**Comment by robmarkcole** [comment]
Hmm the only relevant change I can see is related to https://github.com/home-assistant/core/pull/67837 which was already dealt with

**Comment by holdestmade** [comment]
Apologies, didn't notice your 1.4.1 update, I was on 1.4.0, updated to that and all is working.
