### ISSUE TITLE
Image processing- Scanned Image

### ISSUE THREAD

**Issue by Lezcarr** [robmarkcole/HASS-plate-recognizer#64]
Hi
the image that is scanned from the camera is very low resolution &  fuzzy, the camera is a 8mp camera, any help would be great

**Comment by Lezcarr** [comment]
Hi Robin

Thank you for responding, I am having issues actually getting the
automation to work, I have the motion triggered and it recognises the white
list plate but thats as far as it goes
could you look over this and see where I am going wrong, I really would
appreciate it as been on theis for weeks on & off

lias: Number Plate Recognition
description: ''
trigger:
  - platform: state
    entity_id:
      - camera.carr_home_main_car_park
    to: 'on'
    from: 'off'
condition: []
action:
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_carr_home_front_gate
  - condition: state
    entity_id: sensor.plate_recognizer_3
    state: 'true'
    attribute: xxxxxxMy Plate XXX
  - service: media_player.play_media
    target:
      entity_id: media_player.bathroom_speaker
    data:
      media_content_id: >-

media-source://tts/google_translate?message=Lewis+is+driving+through+the+gate
      media_content_type: provider
    metadata:
      title: Lewis is driving through the gate
      thumbnail:
https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://tts
        - media_content_type: provider
          media_content_id: >-

media-source://tts/google_translate?message=Lewis+is+driving+through+the+gate
  - service: notify.mobile_app_iphone_3
    data:
      message: Lewis is at the gate
      title: Gate Entry
mode: single

**Comment by robmarkcole** [comment]
Not sure, please try the forums
