### ISSUE TITLE
Issue plate start with number

### ISSUE THREAD

**Issue by chimcanhcut1112** [robmarkcole/HASS-plate-recognizer#66]
My country plate start with number like

29a12345

if I put this in template

plate_recognizer:
        friendly_name: "29a12345"
        value_template: "{{ state_attr('image_processing.platerecognizer_frontgate', 'watched_plates').29a12345}}"

will error  

Invalid config for [sensor.template]: invalid template (TemplateSyntaxError: expected name or number) for dictionary value @ data['sensors']['plate_recognizer']['value_template']. Got "{{ state_attr('image_processing.platerecognizer_frontgate', 'watched_plates').'29a12345' }}". (See ?, line ?).

**Comment by robmarkcole** [comment]
duplicates https://github.com/robmarkcole/HASS-plate-recognizer/issues/58
