### ISSUE TITLE
support for image entity type

### ISSUE THREAD

**Issue by geftactics** [robmarkcole/HASS-plate-recognizer#89]
There is a new image.* entity domain in home assistant. Newer versions from frigate make use of this new entity domain for object detections, rather than a camera.* entity.

This component doesn't like it when the supplied entity domain is image.*

Think this will cause a problem for most users that are relying on Frigate to recognise a vehicle to feed into this component...

**Comment by geftactics** [comment]
Went to go and add a long line - but this reveals that it is home assistant `image_processing` that seems to only support cameras, and not the image domain!

```
Invalid config for 'image_processing' at configuration.yaml, line 88: Entity ID 'image.driveway_car' does not belong to domain 'camera' for dictionary value 'source->0->entity_id', got 'image.driveway_car', please check the docs at https://www.home-assistant.io/integrations/image_processing
```

Opened another issue here:
https://github.com/home-assistant/core/issues/111424

**Comment by Nornode** [comment]
@geftactics - Did you ever solve this? 
I commented on the open ticket over at the ticket you opened.

I imagine one can do a workaround and get a camera entitie made from a template and source it with the image entitiy?
Which is definitvely not ideal!...
